spring:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/db.changelog-master.yaml
  mail:
    host: smtp.yandex.ru
    username: tank.33@yandex.ru
    password: 765232wersxcd
    port: 465
    protocol: smtps
jwt:
  token:
    secret: Journal
    duration: 28800000