spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/journal
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/migrations/db.changelog-master.yaml
  mail:
    #    host: smtp.gmail.com
    #    username: vetvet99@gmail.com
    #    password: 765232wersxcd
    #    port: 465
    #    protocol: smtps
    host: smtp.yandex.ru
    username: tank.33@yandex.ru
    password: 765232wersxcd
    port: 465
    protocol: smtps

jwt:
  token:
    secret: Journal
    duration: 1000000000