spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:Journal
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  liquibase:
    enabled: false
  mail:
#    host: smtp.gmail.com
#    username: vetvet99@gmail.com
#    password: 765232wersxcd
#    port: 465
#    protocol: smtps
     host: smtp.yandex.ru
     username: tank.33@yandex.ru
     password: 765232wersxcd
     port: 465
     protocol: smtps

jwt:
  token:
    secret: Journal
    duration: 1000000000